version: '3.9'

services:
  django:
    build: .
    ports: 
      - '8000:8000'
    env_file:
      - venv/.env.production
    depends_on:
      - db
  db:
    image: "postgres:13.0-alpine"
    volumes:
      - psqldata:/var/lib/postgresql/data
    env_file:
      - venv/.env.database


volumes:
  psqldata: