version: '3.9'

services:
  django:
    build: .
    ports: 
      - '8000:8000'
    env_file:
      - venv/.env.dev
    depends_on:
      - db
  db:
    image: "postgres:13.0-alpine"
    volumes:
      - psqldatadev:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=chattradmin
      - POSTGRES_PASSWORD=chattradmin
      - POSTGRES_DB=chattrdev

volumes:
  psqldatadev: